<?php
if (session_status() !== PHP_SESSION_ACTIVE) {
    session_start();
}
$mapsConfigPath = rtrim($_SERVER['DOCUMENT_ROOT'], '/\\') . '/visibility2/portal/config/maps_config.php';
$mapsConfig = is_file($mapsConfigPath) ? include $mapsConfigPath : [];
$mapsKey = is_array($mapsConfig) ? trim((string)($mapsConfig['google_maps_browser_api_key'] ?? $mapsConfig['google_maps_api_key'] ?? '')) : '';
header('Content-Type: text/html; charset=UTF-8');
?>
<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rutas publicadas</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet">
<style>body{background:#f4f7fb;color:#17324d}.page{padding:24px}.card{border:0;border-radius:14px;box-shadow:0 4px 18px rgba(22,50,79,.08)}.card-header{background:#004aad;color:#fff;border-radius:14px 14px 0 0!important;font-weight:700}#map{height:600px;border-radius:12px;background:#e7edf4}.table thead th{background:#0b376b;color:#fff;white-space:nowrap;position:sticky;top:0}.table-responsive{max-height:560px}.route-dot{width:14px;height:14px;border-radius:50%;display:inline-block;margin-right:6px}.metric{background:#fff;border-radius:12px;padding:14px;box-shadow:0 2px 10px rgba(22,50,79,.07)}.metric strong{font-size:1.45rem;color:#004aad}</style></head>
<body><main class="container-fluid page">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-4"><div><h2 class="mb-1"><i class="fa-solid fa-map-location-dot text-primary me-2"></i>Rutas publicadas</h2><div class="text-muted">Consulta sets activos o históricos por división y subdivisión.</div></div><a id="downloadButton" class="btn btn-success disabled" href="#"><i class="fa-solid fa-file-excel me-2"></i>Descargar data</a></div>
<div id="alertBox"></div>
<section class="card mb-4"><div class="card-header"><i class="fa-solid fa-filter me-2"></i>Filtros</div><div class="card-body"><div class="row g-2"><div class="col-lg-3"><label class="form-label small text-muted mb-1">División</label><select id="division" class="form-select"><option value="">Seleccionar división</option></select></div><div class="col-lg-3"><label class="form-label small text-muted mb-1">Subdivisión</label><select id="subdivision" class="form-select" disabled><option value="">Seleccionar subdivisión</option></select></div><div class="col-lg-2"><label class="form-label small text-muted mb-1">Estado</label><select id="status" class="form-select"><option value="activo">Sets activos</option><option value="finalizado">Sets finalizados</option><option value="">Todos</option></select></div><div class="col-lg-4"><label class="form-label small text-muted mb-1">Set de rutas</label><select id="set" class="form-select" disabled><option value="">Seleccionar set</option></select></div><div class="col-lg-4 mt-3"><label class="form-label small text-muted mb-1">Usuario de la ruta</label><select id="routeUser" class="form-select" disabled><option value="">Primero selecciona un set</option></select><div id="userHint" class="small text-muted mt-1"></div></div></div></div></section>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="metric"><span class="text-muted">Locales</span><br><strong id="mLocals">0</strong></div></div><div class="col-md-3"><div class="metric"><span class="text-muted">Usuarios</span><br><strong id="mUsers">0</strong></div></div><div class="col-md-3"><div class="metric"><span class="text-muted">Fechas</span><br><strong id="mDates">0</strong></div></div><div class="col-md-3"><div class="metric"><span class="text-muted">Sin coordenadas</span><br><strong id="mMissing">0</strong></div></div></div>
<div class="row g-4"><div class="col-xl-7"><section class="card"><div class="card-header"><i class="fa-solid fa-map me-2"></i>Mapa de rutas</div><div class="card-body"><div id="map"></div><div id="legend" class="d-flex flex-wrap gap-3 mt-3 small"></div></div></section></div><div class="col-xl-5"><section class="card"><div class="card-header"><i class="fa-solid fa-list-ol me-2"></i>Detalle</div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover table-sm mb-0"><thead><tr><th>Fecha</th><th>Usuario</th><th>Orden</th><th>Local</th></tr></thead><tbody id="detailBody"><tr><td colspan="4" class="text-center text-muted py-4">Selecciona un set.</td></tr></tbody></table></div></div></section></div></div>
</main>
<script>
const API='/visibility2/portal/modulos/mod_panel/rutas_excel_sets_api.php';let map,bounds,markers=[],polylines=[];const palette=['#1473e6','#e53935','#12a150','#ff8c00','#7b1fa2','#008c95','#5d4037','#d81b60','#546e7a','#64b52f'];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));async function json(url){const r=await fetch(url);let d;try{d=await r.json()}catch(e){throw new Error(`Respuesta inválida (HTTP ${r.status}).`)}if(!r.ok||!d.ok)throw new Error(d.message||`HTTP ${r.status}`);return d;}function message(text){document.getElementById('alertBox').innerHTML=`<div class="alert alert-danger">${esc(text)}</div>`;}function fill(el,rows,label){el.innerHTML=`<option value="">${label}</option>`+rows.map(r=>`<option value="${r.id}">${esc(r.nombre||r.name)}</option>`).join('');el.disabled=false;}
function initMap(){map=new google.maps.Map(document.getElementById('map'),{center:{lat:-33.45,lng:-70.66},zoom:6,mapTypeControl:true,streetViewControl:false});}
function clearMap(){markers.forEach(m=>m.setMap(null));polylines.forEach(p=>p.setMap(null));markers=[];polylines=[];bounds=new google.maps.LatLngBounds();}
function resetVisualization(text='Selecciona un usuario para visualizar su ruta.'){clearMap();document.getElementById('legend').innerHTML='';document.getElementById('mLocals').textContent='0';document.getElementById('mUsers').textContent='0';document.getElementById('mDates').textContent='0';document.getElementById('mMissing').textContent='0';document.getElementById('detailBody').innerHTML=`<tr><td colspan="4" class="text-center text-muted py-4">${esc(text)}</td></tr>`;}
function renderRows(rows){clearMap();const groups=new Map(),locals=new Set(),users=new Set(),dates=new Set();let missing=0;rows.forEach(r=>{locals.add(r.id_local);users.add(r.id_usuario);dates.add(r.fecha_visita);const key=`${r.fecha_visita}|${r.id_usuario}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);});let legend='';[...groups.entries()].forEach(([key,group],index)=>{const color=palette[index%palette.length];group.sort((a,b)=>(+a.orden_visita)-(+b.orden_visita));const path=[];group.forEach((r,i)=>{const lat=Number(r.lat),lng=Number(r.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||(lat===0&&lng===0)){missing++;return;}const position={lat,lng};path.push(position);bounds.extend(position);const marker=new google.maps.Marker({map,position,label:{text:String(r.orden_visita>0?r.orden_visita:i+1),color:'#fff',fontWeight:'bold'},title:`${r.codigo_local} - ${r.nombre_local}`,icon:{path:google.maps.SymbolPath.CIRCLE,scale:13,fillColor:color,fillOpacity:1,strokeColor:'#fff',strokeWeight:2}});const info=new google.maps.InfoWindow({content:`<strong>${esc(r.codigo_local)} - ${esc(r.nombre_local)}</strong><br>${esc(r.direccion||'')}<br>${esc(r.usuario_nombre||r.usuario)} · ${esc(r.fecha_visita)}`});marker.addListener('click',()=>info.open({anchor:marker,map}));markers.push(marker);});if(path.length>1){const line=new google.maps.Polyline({map,path,strokeColor:color,strokeOpacity:.85,strokeWeight:4});polylines.push(line);}legend+=`<span><i class="route-dot" style="background:${color}"></i>${esc(group[0].fecha_visita)} · ${esc(group[0].usuario)}</span>`;});if(!bounds.isEmpty())map.fitBounds(bounds);document.getElementById('legend').innerHTML=legend;document.getElementById('mLocals').textContent=locals.size;document.getElementById('mUsers').textContent=users.size;document.getElementById('mDates').textContent=dates.size;document.getElementById('mMissing').textContent=missing;document.getElementById('detailBody').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(r.fecha_visita)}</td><td><strong>${esc(r.usuario)}</strong><div class="small text-muted">${esc(r.usuario_nombre)}</div></td><td>${esc(r.orden_visita||'-')}</td><td><strong>${esc(r.codigo_local)}</strong><div>${esc(r.nombre_local)}</div><div class="small text-muted">${esc(r.comuna||'')}</div></td></tr>`).join(''):'<tr><td colspan="4" class="text-center text-muted py-4">El set no contiene filas.</td></tr>';}
async function loadSets(){const division=document.getElementById('division').value,subdivision=document.getElementById('subdivision').value,status=document.getElementById('status').value,set=document.getElementById('set'),user=document.getElementById('routeUser');user.disabled=true;user.innerHTML='<option value="">Primero selecciona un set</option>';document.getElementById('userHint').textContent='';resetVisualization();if(!division||!subdivision){set.disabled=true;set.innerHTML='<option value="">Seleccionar set</option>';return;}const p=new URLSearchParams({action:'sets',id_division:division,id_subdivision:subdivision});if(status)p.set('estado',status);try{const d=await json(`${API}?${p}`);set.innerHTML='<option value="">Seleccionar set</option>'+d.data.map(r=>`<option value="${r.id}">${esc(r.nombre)} · ${r.estado.toUpperCase()} · ${r.filas_validas} locales</option>`).join('');set.disabled=false;}catch(e){message(e.message);}}
document.getElementById('division').addEventListener('change',async e=>{const sub=document.getElementById('subdivision');sub.disabled=true;sub.innerHTML='<option value="">Cargando...</option>';if(!e.target.value){sub.innerHTML='<option value="">Seleccionar subdivisión</option>';return;}try{const d=await json(`${API}?action=catalogs&id_division=${encodeURIComponent(e.target.value)}`);fill(sub,d.subdivisions,'Seleccionar subdivisión');}catch(err){message(err.message);}});document.getElementById('subdivision').addEventListener('change',loadSets);document.getElementById('status').addEventListener('change',loadSets);
document.getElementById('set').addEventListener('change',async e=>{const button=document.getElementById('downloadButton'),user=document.getElementById('routeUser'),hint=document.getElementById('userHint');resetVisualization();user.disabled=true;user.innerHTML='<option value="">Cargando usuarios...</option>';hint.textContent='';if(!e.target.value){button.classList.add('disabled');user.innerHTML='<option value="">Primero selecciona un set</option>';return;}button.href=`${API}?action=download&id_set=${e.target.value}`;button.classList.remove('disabled');try{const d=await json(`${API}?action=set_users&id_set=${encodeURIComponent(e.target.value)}`);user.innerHTML='<option value="">Seleccionar usuario</option>'+d.data.map(r=>`<option value="${r.id}" data-count="${r.total_locales}" data-dates="${r.total_fechas}" data-from="${r.fecha_desde}" data-to="${r.fecha_hasta}">${esc(r.usuario)} · ${esc(r.nombre||'')} (${r.total_locales})</option>`).join('');user.disabled=false;if(d.data.length===1){user.value=String(d.data[0].id);user.dispatchEvent(new Event('change'));}}catch(err){user.innerHTML='<option value="">No fue posible cargar usuarios</option>';message(err.message);}});
document.getElementById('routeUser').addEventListener('change',async e=>{resetVisualization();const setId=document.getElementById('set').value,hint=document.getElementById('userHint'),option=e.target.selectedOptions[0];if(!setId||!e.target.value){hint.textContent='';return;}hint.textContent=`${option.dataset.count||0} locales · ${option.dataset.dates||0} fechas · ${option.dataset.from||''} a ${option.dataset.to||''}`;document.getElementById('detailBody').innerHTML='<tr><td colspan="4" class="text-center py-4"><span class="spinner-border spinner-border-sm me-2"></span>Cargando ruta...</td></tr>';try{const d=await json(`${API}?action=details&id_set=${encodeURIComponent(setId)}&id_usuario=${encodeURIComponent(e.target.value)}`);renderRows(d.data);}catch(err){message(err.message);resetVisualization('No fue posible cargar la ruta.');}});
(async()=>{try{const d=await json(`${API}?action=catalogs`);fill(document.getElementById('division'),d.divisions,'Seleccionar división');}catch(e){message(e.message)}})();
</script>
<?php if ($mapsKey !== ''): ?><script async defer src="https://maps.googleapis.com/maps/api/js?key=<?= htmlspecialchars($mapsKey, ENT_QUOTES, 'UTF-8') ?>&callback=initMap"></script><?php else: ?><script>message('Falta configurar google_maps_browser_api_key en config/maps_config.php.');</script><?php endif; ?>
</body></html>
