(()=>{
const panel=document.getElementById('panelVisitasLocales');if(!panel)return;
const api=panel.dataset.api||'panel_visitas_data.php';let rows=[],subdivisions=[];
const el=id=>document.getElementById(id),division=el('visdashDivision'),subdivision=el('visdashSubdivision'),campaignStatus=el('visdashCampaignStatus'),loadButton=el('visdashLoad'),feedback=el('visdashFeedback'),userFilter=el('visdashUser'),dateFilter=el('visdashDate');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const pct=(value,total)=>total?value*100/total:0,format=value=>`${value.toFixed(1)}%`;
async function request(url){const response=await fetch(url,{headers:{Accept:'application/json'},cache:'no-store'});let data;try{data=await response.json()}catch{throw new Error(`Respuesta inválida del servidor (HTTP ${response.status}).`)}if(!response.ok||!data.ok)throw new Error(data.message||`Error HTTP ${response.status}.`);return data}
function setFeedback(message,type='neutral'){feedback.textContent=message;feedback.className=`visdash-feedback is-${type}`}
function updateSubdivisions(){const selected=Number(division.value||0),items=subdivisions.filter(item=>item.id_division===selected);subdivision.innerHTML='<option value="">Todas las subdivisiones</option>'+items.map(item=>`<option value="${item.id}">${escapeHtml(item.nombre)}</option>`).join('');subdivision.disabled=!selected}
async function loadCatalogs(){loadButton.disabled=true;try{const response=await request(`${api}?action=catalogs`),data=response.data;subdivisions=data.subdivisions||[];division.innerHTML='<option value="">Seleccionar división</option>'+(data.divisions||[]).map(item=>`<option value="${item.id}">${escapeHtml(item.nombre)}</option>`).join('');if(data.default_division)division.value=String(data.default_division);updateSubdivisions();loadButton.disabled=!division.value;setFeedback(division.value?'Presiona “Cargar registros” para consultar el panel.':'Selecciona una división para comenzar.')}catch(error){division.innerHTML='<option value="">Sin divisiones disponibles</option>';setFeedback(error.message,'error')}}
function populateLocalFilters(){const users=[...new Set(rows.map(row=>row.usuario).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')),dates=[...new Set(rows.map(row=>row.fecha_planificada).filter(Boolean))].sort();userFilter.innerHTML='<option value="">Todos los merchandiser</option>'+users.map(user=>`<option value="${escapeHtml(user)}">${escapeHtml(user)}</option>`).join('');dateFilter.innerHTML='<option value="">Todos los días</option>'+dates.map(date=>`<option value="${date}">${date.split('-').reverse().join('-')}</option>`).join('');userFilter.disabled=!rows.length;dateFilter.disabled=!rows.length;el('visdashUserCount').textContent=`${users.length} merchandiser en los resultados`;el('visdashDateCount').textContent=`${dates.length} días con ruta programada`}
function render(){const filtered=rows.filter(row=>(!userFilter.value||row.usuario===userFilter.value)&&(!dateFilter.value||row.fecha_planificada===dateFilter.value)),total=filtered.length,visited=filtered.filter(row=>row.visitado).length,executed=filtered.filter(row=>row.ejecutado).length,pending=Math.max(0,total-visited),visitedPct=pct(visited,total),executedPct=pct(executed,total),pendingPct=pct(pending,total);el('kpiVisited').textContent=format(visitedPct);el('kpiExecuted').textContent=format(executedPct);el('kpiPending').textContent=format(pendingPct);el('kpiVisitedDetail').textContent=`${visited} de ${total} locales programados`;el('kpiExecutedDetail').textContent=`${executed} gestiones válidas del programa`;el('kpiPendingDetail').textContent=`${pending} locales sin visitar`;el('barVisited').style.width=`${visitedPct}%`;el('barExecuted').style.width=`${executedPct}%`;el('barPending').style.width=`${pendingPct}%`;el('visdashSubtitle').textContent=`Cumplimiento de rutas · ${userFilter.value||'todos los merchandiser'} · ${dateFilter.value?dateFilter.value.split('-').reverse().join('-'):'todos los días'}`;
const bars=[['Visitados',visitedPct,'#12a77c'],['Pendientes',pendingPct,'#efa93e'],['Ejecutados',executedPct,'#087f96']];el('complianceChart').innerHTML=bars.map(([label,value,color])=>`<div class="vbar-item"><strong style="color:${color}">${format(value)}</strong><div class="vbar" style="height:${Math.max(2,value)}%;background:${color}"></div><span>${label}</span></div>`).join('');
const visitedRows=filtered.filter(row=>row.visitado),statusCounts={};visitedRows.forEach(row=>statusCounts[row.estado]=(statusCounts[row.estado]||0)+1);const statuses=Object.entries(statusCounts).sort((a,b)=>b[1]-a[1]);el('statusChart').innerHTML=statuses.length?statuses.map(([status,count])=>{const value=pct(count,visitedRows.length);return`<div class="hbar-row" title="${escapeHtml(status)}"><span>${escapeHtml(status)}</span><div class="hbar-track"><div class="hbar-fill" style="width:${value}%"></div></div><strong>${format(value)}</strong></div>`}).join(''):'<div class="visdash-empty">Sin locales visitados para estos filtros.</div>';
const merch={};filtered.forEach(row=>{const item=merch[row.usuario]||(merch[row.usuario]={total:0,visited:0});item.total++;if(row.visitado)item.visited++});const merchRows=Object.entries(merch).sort((a,b)=>pct(b[1].visited,b[1].total)-pct(a[1].visited,a[1].total)||a[0].localeCompare(b[0],'es'));el('merchTableBody').innerHTML=merchRows.length?merchRows.map(([user,item])=>`<tr><td>${escapeHtml(user)}</td><td>${item.total-item.visited}</td><td>${item.visited}</td><td>${item.total}</td><td>${format(pct(item.visited,item.total))}</td></tr>`).join(''):'<tr><td colspan="5" class="visdash-empty">Sin información.</td></tr>';el('statusTableCaption').textContent=`Porcentaje sobre ${visitedRows.length} locales visitados.`;el('statusTableBody').innerHTML=statuses.length?statuses.map(([status,count])=>`<tr><td>${escapeHtml(status)}</td><td>${count}</td><td>${format(pct(count,visitedRows.length))}</td></tr>`).join(''):'<tr><td colspan="3" class="visdash-empty">Sin estados de gestión.</td></tr>'}
async function loadRows(){if(!division.value){setFeedback('Selecciona una división.','error');return}loadButton.disabled=true;loadButton.textContent='Cargando...';setFeedback('Consultando campañas y rutas...','loading');const params=new URLSearchParams({action:'data',id_division:division.value,estado:campaignStatus.value});if(subdivision.value)params.set('id_subdivision',subdivision.value);try{const response=await request(`${api}?${params}`);rows=response.data||[];populateLocalFilters();render();setFeedback(rows.length?`${rows.length.toLocaleString('es-CL')} locales cargados correctamente.`:'No se encontraron registros para los filtros seleccionados.',rows.length?'success':'neutral')}catch(error){rows=[];populateLocalFilters();render();setFeedback(error.message,'error')}finally{loadButton.disabled=false;loadButton.textContent='Cargar registros'}}
division.addEventListener('change',()=>{updateSubdivisions();loadButton.disabled=!division.value;rows=[];populateLocalFilters();render();setFeedback(division.value?'Presiona “Cargar registros” para consultar el panel.':'Selecciona una división para comenzar.')});loadButton.addEventListener('click',loadRows);userFilter.addEventListener('change',render);dateFilter.addEventListener('change',render);render();loadCatalogs();
})();
